export const TITLES = {
  Director: { id: 1, name: 'Director' },
  DirectorOfPhotography: { id: 2, name: 'Director of Photography' },
  Producer: { id: 3, name: 'Producer' },
  Editor: { id: 4, name: 'Editor' },
  Colorist: { id: 5, name: 'Colorist' },
  Composer: { id: 6, name: 'Composer' },
  Photographer: { id: 7, name: 'Director' },
  Retoucher: { id: 8, name: 'Retoucher' },
  CEO: { id: 9, name: 'CEO' },
  ManagingDirector: { id: 10, name: 'Managing Director' },
  ChiefCreativeOfficer: { id: 11, name: 'Chief Creative Officer' },
  ExecutiveCreativeDirector: { id: 12, name: 'Executive Creative Director' },
  CreativeDirector: { id: 13, name: 'Creative Director' },
  ArtDirector: { id: 14, name: 'Art Director' },
  Copywriter: { id: 15, name: 'Copywriter' },
  AccountDirector: { id: 16, name: 'Account Director' },
  AccountManager: { id: 17, name: 'Account Manager' },
  AgencyProducer: { id: 18, name: 'Agency Producer' },
  Illustrator: { id: 19, name: 'Illustrator' },
  GraphicDesigner: { id: 20, name: 'Graphic Designer' },
};
